Repository PicadaARSW/MazorcaUsers, pull requests merged in 2025-04, with the labels that each got.

#9 ADD: swagger and file env
  .env
  .gitignore
  pom.xml
  src/main/java/arsw/wherewe/back/mazorcausers/config/DotEnvConfig.java
  src/main/java/arsw/wherewe/back/mazorcausers/config/SwaggerConfig.java
  src/main/java/arsw/wherewe/back/mazorcausers/controller/UserController.java
  src/main/java/arsw/wherewe/back/mazorcausers/model/User.java
  src/main/resources/application.yml
Labels: duplicate

#10 FIX TESTS AND PIPELINE
  .github/workflows/sonarCloud.yml
  .gitignore
  src/test/java/arsw/wherewe/back/mazorcausers/controller/UserControllerTests.java
Labels: bug

#11 Release
  .env
  .github/workflows/sonarCloud.yml
  .gitignore
  Dockerfile
  LICENSE.txt
  META-INF/MANIFEST.MF
  pom.xml
  src/main/java/arsw/wherewe/back/mazorcausers/config/CorsConfig.java
  src/main/java/arsw/wherewe/back/mazorcausers/config/DotEnvConfig.java
  src/main/java/arsw/wherewe/back/mazorcausers/config/SwaggerConfig.java
  src/main/java/arsw/wherewe/back/mazorcausers/controller/UserController.java
  src/main/java/arsw/wherewe/back/mazorcausers/model/User.java
  src/main/java/arsw/wherewe/back/mazorcausers/service/UserService.java
  src/main/resources/application.yml
  src/test/java/arsw/wherewe/back/mazorcausers/MazorcausersApplicationTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/controller/UserControllerTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/model/UserTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/service/UserServiceTest.java
Labels: documentation

#12 FIX-issue-sonarcloud
  src/main/java/arsw/wherewe/back/mazorcausers/controller/UserController.java
  src/main/java/arsw/wherewe/back/mazorcausers/dto/UserDTO.java
  src/main/java/arsw/wherewe/back/mazorcausers/service/UserService.java
  src/test/java/arsw/wherewe/back/mazorcausers/controller/UserControllerTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/dto/UserDTOTest.java
  src/test/java/arsw/wherewe/back/mazorcausers/service/UserServiceTest.java
Labels: duplicate

#13 Release
  src/main/java/arsw/wherewe/back/mazorcausers/controller/UserController.java
  src/main/java/arsw/wherewe/back/mazorcausers/dto/UserDTO.java
  src/main/java/arsw/wherewe/back/mazorcausers/service/UserService.java
  src/test/java/arsw/wherewe/back/mazorcausers/controller/UserControllerTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/dto/UserDTOTest.java
  src/test/java/arsw/wherewe/back/mazorcausers/service/UserServiceTest.java
Labels: duplicate

#14 FIX-issue-sonarcloud
  src/main/java/arsw/wherewe/back/mazorcausers/config/CorsConfig.java
Labels: duplicate

#15 Release
  src/main/java/arsw/wherewe/back/mazorcausers/config/CorsConfig.java
Labels: duplicate

#16 Create README.md
  README.md
Labels: documentation

#17 ADD: feature delete user and change profile picture
  src/main/java/arsw/wherewe/back/mazorcausers/controller/UserController.java
  src/main/java/arsw/wherewe/back/mazorcausers/dto/UserDTO.java
  src/main/java/arsw/wherewe/back/mazorcausers/model/User.java
  src/main/java/arsw/wherewe/back/mazorcausers/service/UserService.java
  src/test/java/arsw/wherewe/back/mazorcausers/controller/UserControllerTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/dto/UserDTOTest.java
  src/test/java/arsw/wherewe/back/mazorcausers/model/UserTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/service/UserServiceTest.java
Labels: feature

#18 ADD:authorization jwt
  pom.xml
  src/main/java/arsw/wherewe/back/mazorcausers/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: feature

#19 Feature/add deploy
  .env
  pom.xml
  src/main/java/arsw/wherewe/back/mazorcausers/config/DotEnvConfig.java
  src/test/java/arsw/wherewe/back/mazorcausers/MazorcausersApplicationTests.java
Labels: feature

#20 Release
  .env
  README.md
  pom.xml
  src/main/java/arsw/wherewe/back/mazorcausers/config/DotEnvConfig.java
  src/main/java/arsw/wherewe/back/mazorcausers/config/SecurityConfig.java
  src/main/java/arsw/wherewe/back/mazorcausers/controller/UserController.java
  src/main/java/arsw/wherewe/back/mazorcausers/dto/UserDTO.java
  src/main/java/arsw/wherewe/back/mazorcausers/model/User.java
  src/main/java/arsw/wherewe/back/mazorcausers/service/UserService.java
  src/main/resources/application.yml
  src/test/java/arsw/wherewe/back/mazorcausers/MazorcausersApplicationTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/controller/UserControllerTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/dto/UserDTOTest.java
  src/test/java/arsw/wherewe/back/mazorcausers/model/UserTests.java
  src/test/java/arsw/wherewe/back/mazorcausers/service/UserServiceTest.java
Labels: feature

#21 Fix gitignore
  .gitignore
Labels: feature
